version: "3"
services:
  city-suggestion-service:
    build: ./
    volumes:
      - ./:/code
    ports:
      - "8080:8080"
    env_file:
      - ./env/city-suggestion-service.env
    command: npm run dev
